name: Validate action
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  default-parameters:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: configure-pagefile-action
      uses: ./
      with:
        minimum-size: 8GB

    - name: validation
      shell: pwsh
      run: |
        (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
        Invoke-Expression "wmic pagefile list /format:list" | Select-String "AllocatedBaseSize=", "Name="

  custom-parameters:
    strategy:
      matrix:
        os: [ windows-2022, windows-2019 ]
        disk-root: [ "C:" ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: configure-pagefile-action
      uses: ./
      with:
        minimum-size: 4GB
        maximum-size: 8GB
        disk-root: ${{ matrix.disk-root }}

    - name: validation
      shell: pwsh
      run: |
        (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
        Invoke-Expression "wmic pagefile list /format:list" | Select-String "AllocatedBaseSize=", "Name="
